// <auto-generated />
using System;
using InfoTechCoreMVCCodeFirstFluent09062024.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoTechCoreMVCCodeFirstFluent09062024.Migrations
{
    [DbContext(typeof(UniContext))]
    [Migration("20240609080554_baslangic")]
    partial class baslangic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Category", b =>
                {
                    b.Property<int>("CatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatID"), 1L, 1);

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("CatID");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Egitmen", b =>
                {
                    b.Property<int>("EgitmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenID"), 1L, 1);

                    b.Property<string>("EgitmenAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Adi");

                    b.Property<string>("EgitmenSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Soyadi");

                    b.HasKey("EgitmenID");

                    b.ToTable("Egitmen");
                });

            modelBuilder.Entity("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"), 1L, 1);

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Adi");

                    b.Property<string>("OgrenciSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Soyadi");

                    b.HasKey("OgrenciID");

                    b.ToTable("Ogrencilerimiz", (string)null);
                });

            modelBuilder.Entity("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<int>("CatID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("UnitInStock")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("CatID");

                    b.ToTable("Urunler", (string)null);
                });

            modelBuilder.Entity("OgrenciEgitmen", b =>
                {
                    b.Property<int>("EgitmenID")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.HasKey("EgitmenID", "OgrenciID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("OgrenciEgitmen");
                });

            modelBuilder.Entity("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Product", b =>
                {
                    b.HasOne("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OgrenciEgitmen", b =>
                {
                    b.HasOne("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Egitmen", null)
                        .WithMany()
                        .HasForeignKey("EgitmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoTechCoreMVCCodeFirstFluent09062024.Models.Entities.Category", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
