// <auto-generated />
using System;
using IA_ECommerceProject_13072024.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IA_ECommerceProject_13072024.Migrations
{
    [DbContext(typeof(ETicaretContext))]
    [Migration("20240713090803_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"), 1L, 1);

                    b.Property<string>("KategoriAciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoris");

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAciklamasi = "Elektronik Ürünler",
                            KategoriAdi = "Elektronik"
                        });
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rolu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicis");

                    b.HasData(
                        new
                        {
                            KullaniciID = 1,
                            Adi = "Ali",
                            KullaniciAdi = "aliyilmaz",
                            Parola = "12345",
                            Rolu = "Admin",
                            Soyadi = "Yılmaz"
                        });
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Sepet", b =>
                {
                    b.Property<int>("SepetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SepetID"), 1L, 1);

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("RefKullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("RefUrunID")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SepetID");

                    b.HasIndex("RefKullaniciID");

                    b.HasIndex("RefUrunID");

                    b.ToTable("Sepets");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefKullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("SiparisID");

                    b.HasIndex("RefKullaniciID");

                    b.ToTable("Sipariss");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.SiparisKalem", b =>
                {
                    b.Property<int>("SiparisKalemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisKalemID"), 1L, 1);

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("RefSiparisID")
                        .HasColumnType("int");

                    b.Property<int>("RefUrunID")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SiparisKalemID");

                    b.HasIndex("RefSiparisID");

                    b.HasIndex("RefUrunID");

                    b.ToTable("SiparisKalems");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"), 1L, 1);

                    b.Property<int>("RefKategoriID")
                        .HasColumnType("int");

                    b.Property<string>("UrunAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("UrunFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunFoto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UrunID");

                    b.HasIndex("RefKategoriID");

                    b.ToTable("Uruns");

                    b.HasData(
                        new
                        {
                            UrunID = 1,
                            RefKategoriID = 1,
                            UrunAciklama = "Test",
                            UrunAdi = "Laptop",
                            UrunFiyati = 35000m
                        });
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Sepet", b =>
                {
                    b.HasOne("IA_ECommerceProject_13072024.Models.Entities.Kullanici", "Kullanici")
                        .WithMany("Sepet")
                        .HasForeignKey("RefKullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IA_ECommerceProject_13072024.Models.Entities.Urun", "Urun")
                        .WithMany("Sepet")
                        .HasForeignKey("RefUrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Siparis", b =>
                {
                    b.HasOne("IA_ECommerceProject_13072024.Models.Entities.Kullanici", "Kullanici")
                        .WithMany("Siparis")
                        .HasForeignKey("RefKullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.SiparisKalem", b =>
                {
                    b.HasOne("IA_ECommerceProject_13072024.Models.Entities.Siparis", "Siparis")
                        .WithMany("SiparisKalem")
                        .HasForeignKey("RefSiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IA_ECommerceProject_13072024.Models.Entities.Urun", "Urun")
                        .WithMany("SiparisKalem")
                        .HasForeignKey("RefUrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Urun", b =>
                {
                    b.HasOne("IA_ECommerceProject_13072024.Models.Entities.Kategori", "Kategori")
                        .WithMany("Urun")
                        .HasForeignKey("RefKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Kategori", b =>
                {
                    b.Navigation("Urun");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Kullanici", b =>
                {
                    b.Navigation("Sepet");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Siparis", b =>
                {
                    b.Navigation("SiparisKalem");
                });

            modelBuilder.Entity("IA_ECommerceProject_13072024.Models.Entities.Urun", b =>
                {
                    b.Navigation("Sepet");

                    b.Navigation("SiparisKalem");
                });
#pragma warning restore 612, 618
        }
    }
}
