// <auto-generated />
using System;
using InfoTechDataAnotation09062024.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoTechDataAnotation09062024.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Islem", b =>
                {
                    b.Property<int>("IslemNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemNo"), 1L, 1);

                    b.Property<DateTime>("ATarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KitapNo")
                        .HasColumnType("int");

                    b.Property<int>("OgrNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("VTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("IslemNo");

                    b.HasIndex("KitapNo");

                    b.HasIndex("OgrNo");

                    b.ToTable("Islems");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Kitap", b =>
                {
                    b.Property<int>("KitapNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapNo"), 1L, 1);

                    b.Property<string>("IsbnNo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Puan")
                        .HasColumnType("tinyint");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TurNo")
                        .HasColumnType("int");

                    b.Property<int>("YazarNo")
                        .HasColumnType("int");

                    b.HasKey("KitapNo");

                    b.HasIndex("TurNo");

                    b.HasIndex("YazarNo");

                    b.ToTable("Kitaps");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrNo"), 1L, 1);

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Puan")
                        .HasColumnType("tinyint");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OgrNo");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Tur", b =>
                {
                    b.Property<int>("TurNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurNo"), 1L, 1);

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurNo");

                    b.ToTable("Turs");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Yazar", b =>
                {
                    b.Property<int>("YazarNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarNo"), 1L, 1);

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YazarSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("YazarNo");

                    b.ToTable("Yazars");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Islem", b =>
                {
                    b.HasOne("InfoTechDataAnotation09062024.Models.Entities.Kitap", "Kitap")
                        .WithMany("Islems")
                        .HasForeignKey("KitapNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTechDataAnotation09062024.Models.Entities.Ogrenci", "Ogrenci")
                        .WithMany("Islems")
                        .HasForeignKey("OgrNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Kitap", b =>
                {
                    b.HasOne("InfoTechDataAnotation09062024.Models.Entities.Tur", "Tur")
                        .WithMany("Kitaps")
                        .HasForeignKey("TurNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTechDataAnotation09062024.Models.Entities.Yazar", "Yazar")
                        .WithMany("Kitaps")
                        .HasForeignKey("YazarNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tur");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Kitap", b =>
                {
                    b.Navigation("Islems");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Ogrenci", b =>
                {
                    b.Navigation("Islems");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Tur", b =>
                {
                    b.Navigation("Kitaps");
                });

            modelBuilder.Entity("InfoTechDataAnotation09062024.Models.Entities.Yazar", b =>
                {
                    b.Navigation("Kitaps");
                });
#pragma warning restore 612, 618
        }
    }
}
